language: python
python:
  - 2.6
  - 2.7
env:
    global:
        - LMOD_VERSION=5.6.3
        - ENV_MOD_INIT=$HOME/Modules/3.2.10/init/bash
        - LMOD_INIT=$HOME/lmod/$LMOD_VERSION/init/bash
    matrix:
        # each of these configurations will be tested, for each Python version
        - MOD_INIT=$ENV_MOD_INIT
        #- MOD_INIT=$LMOD_INIT TEST_EASYBUILD_MODULES_TOOL=Lmod
        #- MOD_INIT=$LMOD_INIT TEST_EASYBUILD_MODULES_TOOL=Lmod EASYBUILD_MODULE_SYNTAX=Lua
addons:
  apt:
    packages:
      # for environment modules/Lmod
      - tcl8.5
      # for EasyBuild
      - python-setuptools
before_install:
    # keyring is required to provide GitHub token to EasyBuild
    - pip install keyring==5.7.1
    # optional Python packages for EasyBuild
    - pip install autopep8 GC3Pie GitPython PyYAML
install:
    - easy_install vsc-base
    # install environment modules
    - wget http://prdownloads.sourceforge.net/modules/modules-3.2.10.tar.gz
    - tar xfz modules-3.2.10.tar.gz && cd modules-3.2.10
    - ./configure --prefix=$HOME && make && make install
    # install Lua that includes required Lua packages provided by Lmod
    - wget http://downloads.sourceforge.net/project/lmod/lua-5.1.4.8.tar.gz
    - tar xfz lua-5.1.4.8.tar.gz && cd lua-5.1.4.8
    - ./configure --with-static=yes --prefix=$HOME && make && make install
    - export PATH=$HOME/bin:$PATH
    # install Lmod
    - wget https://github.com/TACC/Lmod/archive/${LMOD_VERSION}.tar.gz
    - tar xfz ${LMOD_VERSION}.tar.gz && cd Lmod-${LMOD_VERSION}
    - ./configure --prefix=$HOME && make install
script:
    # set up environment for modules tool
    - export PATH=$HOME/Modules/3.2.10/bin:$HOME/lmod/$LMOD_VERSION/libexec:$PATH
    - source $MOD_INIT
    - ls -l $(which lmod)
    - lmod python --version
    - echo $LMOD_CMD
    - echo $MODULEPATH
    - echo $MODULEPATH | tr ':' ' ' | xargs ls -l
    # set up environment for EasyBuild framework tests
    - export PATH=$TRAVIS_BUILD_DIR:$PATH
    - export PYTHONPATH=$TRAVIS_BUILD_DIR
    # framework tests can not be run in cloned repository, due to Python packaging weirdness
    - cd $HOME
    # install GitHub token
    - python -c "import keyring; keyring.set_keyring(keyring.backends.file.PlaintextKeyring());
                 keyring.set_password('github_token', 'easybuild_test', '$GITHUB_TOKEN')"
    # TEST!
    - python -O -m test.framework.suite
