language: python
python: 2.6
matrix:
  include:
    - env: ENV_MOD_VERSION=3.2.10 MOD_INIT=$HOME/Modules/$ENV_MOD_VERSION/init/bash
    - python: 2.7
      env: ENV_MOD_VERSION=3.2.10 MOD_INIT=$HOME/Modules/$ENV_MOD_VERSION/init/bash
    - env: LMOD_VERSION=5.6.3 TEST_EASYBUILD_MODULES_TOOL=Lmod MOD_INIT=$HOME/lmod/$LMOD_VERSION/init/bash
    - env: LMOD_VERSION=5.6.3 TEST_EASYBUILD_MODULES_TOOL=Lmod TEST_EASYBUILD_MODULE_SYNTAX=Lua MOD_INIT=$HOME/lmod/$LMOD_VERSION/init/bash
    - env: LMOD_VERSION=6.1 TEST_EASYBUILD_MODULES_TOOL=Lmod TEST_EASYBUILD_MODULE_SYNTAX=Lua MOD_INIT=$HOME/lmod/$LMOD_VERSION/init/bash
addons:
  apt:
    packages:
      # for environment modules/Lmod
      - tcl8.5
      # for EasyBuild
      - python-setuptools
      # for GitPython
      - git
      # for GC3Pie (optional dep for EasyBuild)
      - time
before_install:
    # keyring is required to provide GitHub token to EasyBuild;
    # keyring v5.7.1 is last version to be compatible with both py2.6 and py2.7
    - pip install keyring==5.7.1
    # optional Python packages for EasyBuild
    - pip install autopep8 GC3Pie GitPython python-graph-dot python-hglib PyYAML
    # git config is required to make actual git commits (cfr. tests for GitRepository)
    - git config --global user.name "Travis CI"
    - git config --global user.email "travis@travis-ci.org"
install:
    # install vsc-base (& vsc-install) dependencies for EasyBuild
    - easy_install vsc-base
    # install environment modules
    - if [ ! -z $ENV_MOD_VERSION ]; then
      wget http://prdownloads.sourceforge.net/modules/modules-${ENV_MOD_VERSION}.tar.gz;
      tar xfz modules-${ENV_MOD_VERSION}.tar.gz && cd modules-${ENV_MOD_VERSION};
      ./configure --prefix=$HOME && make && make install;
      export PATH=$HOME/Modules/$ENV_MOD_VERSION/bin:PATH;
      fi
    - if [ ! -z $LMOD_VERSION ]; then
      # install Lua that includes required Lua packages (provided by Lmod)
      wget http://downloads.sourceforge.net/project/lmod/lua-5.1.4.8.tar.gz;
      tar xfz lua-5.1.4.8.tar.gz && cd lua-5.1.4.8;
      ./configure --with-static=yes --prefix=$HOME && make && make install;
      export PATH=$HOME/bin:$PATH;
      # install Lmod
      wget https://github.com/TACC/Lmod/archive/${LMOD_VERSION}.tar.gz;
      tar xfz ${LMOD_VERSION}.tar.gz && cd Lmod-${LMOD_VERSION};
      ./configure --prefix=$HOME && make install;
      export PATH=$HOME/lmod/$LMOD_VERSION/libexec:$PATH;
      fi
script:
    # set up environment for modules tool
    - source $MOD_INIT
    # set up environment for EasyBuild framework tests
    - export PATH=$TRAVIS_BUILD_DIR:$PATH; export PYTHONPATH=$TRAVIS_BUILD_DIR
    # install GitHub token
    - python -c "import keyring; keyring.set_keyring(keyring.backends.file.PlaintextKeyring());
                 keyring.set_password('github_token', 'easybuild_test', '$GITHUB_TOKEN')"
    # run test suite
    # framework tests can not be run in cloned repository, due to Python packaging weirdness
    - cd $HOME; python -O -m test.framework.suite; cd -
    # test bootstrap script
    - if [ ! -z $TEST_EASYBUILD_MODULES_TOOL ]; then EASYBUILD_MODULES_TOOL=$TEST_EASYBUILD_MODULES_TOOL; fi
    - if [ ! -z $TEST_EASYBUILD_MODULE_SYNTAX ]; then EASYBUILD_MODULE_SYNTAX=$TEST_EASYBUILD_MODULE_SYNTAX; fi
    - python $TRAVIS_BUILD_DIR/easybuild/scripts/bootstrap_eb.py /tmp/$TRAVIS_JOB_ID
    - module use /tmp/$TRAVIS_JOB_ID/modules/all; module load EasyBuild; eb --version
