name: EasyBuild framework unit tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7]
        modules_tool: [Lmod-6.6.3, Lmod-7.8.22, Lmod-8.1.14]
        module_syntax: [Lua, Tcl]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1

    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
        architecture: x64

    - name: install OS & Python packages
      run: |
        # for modules tool
        sudo apt-get install lua5.1 liblua5.1-0-dev lua-filesystem lua-posix lua-filesystem tcl
        sudo ln -s /usr/lib/x86_64-linux-gnu/lua/5.1/posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.1/posix.so
        # for GitPython, python-hglib
        sudo apt-get install git mercurial
        # dep for GC3Pie
        sudo apt-get install time
        # Python packages
        pip --version
        pip install --upgrade pip
        pip --version
        pip install -r requirements.txt
        # git config is required to make actual git commits (cfr. tests for GitRepository)
        git config --global user.name "Travis CI"
        git config --global user.email "travis@travis-ci.org"
        git config --get-regexp 'user.*'

    - name: install GitHub token (if available)
      env:
        # see https://github.com/<username>/easybuild-framework/settings/secrets
        GITHUB_TOKEN: ${{secrets.TEST_GITHUB_TOKEN}}
      run: |
        if [ ! -z $GITHUB_TOKEN ]; then
          if [ "x${{matrix.python}}" == 'x2.6' ];
              then SET_KEYRING="keyring.set_keyring(keyring.backends.file.PlaintextKeyring())";
              else SET_KEYRING="import keyrings; keyring.set_keyring(keyrings.alt.file.PlaintextKeyring())";
          fi;
          python -c "import keyring; $SET_KEYRING; keyring.set_password('github_token', 'easybuild_test', '$GITHUB_TOKEN')";
        fi

    - name: install modules tool
      run: |
          export INSTALL_DEP=$GITHUB_WORKSPACE/easybuild/scripts/install_eb_dep.sh
          # install Lmod
          source $INSTALL_DEP ${{matrix.modules_tool}} $HOME
          # changes in environment are not passed to other steps, so need to create a file for $MOD_INIT
          echo $MOD_INIT > mod_init

    - name: run test suite
      env:
        TEST_EASYBUILD_MODULE_SYNTAX: ${{matrix.module_syntax}}
      run: |
          # initialize environment for modules tool
          source $(cat mod_init); type module
          # make sure 'eb' is available via $PATH, and that $PYTHONPATH is set (some tests expect that)
          export PATH=$PWD:$PATH
          export PYTHONPATH=$PWD
          # gather some useful info on test system
          eb --show-system-info
          # check GitHub configuration
          eb --check-github --github-user=easybuild_test
          # run test suite
          python -O -m test.framework.suite
