name: EasyBuild framework unit tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [2.7, 3.6]
        lmod_version: [7.8.22]
        module_syntax: [Lua]
    steps:
    - uses: actions/checkout@v1
    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
        architecture: x64
    - name: install packages
      run:
        sudo apt-get install tcl lua5.1 liblua5.1-0-dev lua-posix lua-filesystem git mercurial time;
        sudo ln -s /usr/lib/x86_64-linux-gnu/lua/5.1/posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.1/posix.so;
    - name: test 'eb' command
      run: EB_PYTHON=python ./eb --show-system-info
    - name: install modules tool + run test suite
      run: |
          # install Lmod
          source $GITHUB_WORKSPACE/easybuild/scripts/install_eb_dep.sh Lmod-${{matrix.lmod_version}} $HOME
          # initialize environment for modules tool
          if [ ! -z $MOD_INIT ]; then source $MOD_INIT; type module; fi
          # configure EasyBuild
          export TEST_EASYBUILD_MODULE_SYNTAX=${{matrix.module_syntax}}
          # run test suite
          python -O -m test.framework.modules
