name: EasyBuild framework unit tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [2.7, 3.6]
        lmod_version: [6.5.1, 7.8.22, 8.0.9]
        module_syntax: [Tcl, Lua]
        include:
            - python: 3.5
              lmod_version: 7.8.22
              module_syntax: Lua
            - python: 3.7
              lmod_version: 7.8.22
              module_syntax: Lua
    steps:
    - uses: actions/checkout@v1
    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
        architecture: x64
    - name: test 'eb' command
      run: EB_PYTHON=python ./eb --show-system-info
    - name: install dependencies
      run:
          export INSTALL_DEP=$GITHUB_WORKSPACE/easybuild/scripts/install_eb_dep.sh;
          source $INSTALL_DEP lua-5.1.4.8 $HOME;
          source $INSTALL_DEP Lmod-${{matrix.lmod_version}} $HOME
    - name: easybuild-framework test suite
      run:
          export TEST_EASYBUILD_MODULE_SYNTAX=${{matrix.module_syntax}}
          python -O -m test.framework.modules
